services:
    app:
        image: us-docker.pkg.dev/test001-397012/docker-1/barefoot-mosquitoes-workwave:${GH_REF-master}
        build: .
        volumes:
            - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
            K_SERVICE: dev
            K_CONFIGURATION: dev
            K_REVISION: dev-00001
        ports:
            - 8080:8080
