import { BooleanField, Int64Field, NumericField, RecordField, StringField, DateTimeField } from '../schema';
import { createWebhookModel } from '../webhook.interface';

const PdfUrlFields = [
    new StringField('AdditionalProp1'),
    new StringField('AdditionalProp2'),
    new StringField('AdditionalProp3'),
    new StringField('Invoice'),
    new StringField('InspectionReport'),
];

const TaxDetailsFields = [
    new StringField('CountryOfTax'),
    new StringField('TaxLabel'),
    new NumericField('TaxRate'),
    new NumericField('TaxAmount'),
];

const UserDefinedFields = [
    new Int64Field('FieldNum'),
    new StringField('Caption'),
    new StringField('Value'),
    new StringField('Description'),
    new StringField('Type'),
    new BooleanField('Show'),
    new StringField('TableName'),
];

export const Invoice = createWebhookModel({
    name: 'Invoice',
    resolver: (id) => ({ method: 'GET', url: `invoices/${id}` }),
    fields: [
        new Int64Field('InvoiceID'),
        new Int64Field('LocationID'),
        new Int64Field('BillToID'),
        new Int64Field('SetupID'),
        new StringField('InvoiceNumber'),
        new StringField('OrderNumber'),
        new StringField('Branch'),
        new Int64Field('BranchID'),
        new RecordField('ServiceLocation', [
            new StringField('Company'),
            new StringField('LName'),
            new StringField('FName'),
            new StringField('Title'),
            new StringField('Address'),
            new StringField('Address2'),
            new StringField('City'),
            new StringField('State'),
            new StringField('Zip'),
        ]),
        new RecordField('BillTo', [
            new StringField('Company'),
            new StringField('LName'),
            new StringField('FName'),
            new StringField('Title'),
            new StringField('Address'),
            new StringField('Address2'),
            new StringField('City'),
            new StringField('State'),
            new StringField('Zip'),
        ]),
        new StringField('ServiceCode'),
        new StringField('Description'),
        new NumericField('TaxRate'),
        new NumericField('SubTotal'),
        new NumericField('Tax'),
        new RecordField('TaxDetails', TaxDetailsFields, true),
        new NumericField('Total'),
        new NumericField('Balance'),
        new NumericField('Cost'),
        new DateTimeField('InvoiceDate'),
        new DateTimeField('WorkDate'),
        new DateTimeField('DueDate'),
        new StringField('TimeRange'),
        new NumericField('Duration'),
        new StringField('InvoiceType'),
        new StringField('OrderType'),
        new StringField('SetupType'),
        new DateTimeField('OrderDate'),
        new StringField('Origin'),
        new StringField('Route'),
        new NumericField('Measurement'),
        new StringField('MeasurementType'),
        new StringField('TaxCode'),
        new StringField('PurchaseOrderNumber'),
        new StringField('Division'),
        new StringField('Source'),
        new StringField('GLCode'),
        new Int64Field('ParentInvoiceID'),
        new StringField('LocationInstructions'),
        new StringField('ServiceInstructions'),
        new StringField('OrderInstructions'),
        new StringField('TechnicianComment'),
        new BooleanField('Printed'),
        new DateTimeField('PrintedDate'),
        new StringField('Terms'),
        new StringField('CreditMemoReason'),
        new BooleanField('TaxOnlyCreditMemo'),
        new Int64Field('BatchNumber'),
        new BooleanField('Void'),
        new StringField('NotServicedReason'),
        new StringField('ConsolidatedInvoiceNum'),
        new DateTimeField('ConsolidatedInvoiceDate'),
        new RecordField(
            'LineItems',
            [
                new StringField('ServiceCode'),
                new StringField('Description'),
                new NumericField('Cost'),
                new NumericField('UnitPrice'),
                new NumericField('Quantity'),
                new NumericField('ExtendedPrice'),
                new BooleanField('Taxable'),
                new StringField('GLCode'),
            ],
            true,
        ),
        new RecordField(
            'MaterialApplications',
            [
                new Int64Field('MaterialApplicationID'),
                new Int64Field('OrderID'),
                new Int64Field('OrderNum'),
                new Int64Field('InvoiceID'),
                new Int64Field('InvoiceNum'),
                new Int64Field('LocationID'),
                new Int64Field('MaterialID'),
                new StringField('MaterialCode'),
                new StringField('MaterialName'),
                new StringField('LotNumber'),
                new StringField('EPARegistration'),
                new NumericField('Quantity'),
                new StringField('UnitOfMeasure'),
                new NumericField('UndilutedQuantity'),
                new StringField('UndilutedUnitOfMeasure'),
                new StringField('ActiveIngredient'),
                new NumericField('ActiveIngredientPercentage'),
                new NumericField('ActiveIngredientConcentration'),
                new StringField('ApplicationRate'),
                new StringField('ApplicationMethod'),
                new StringField('ApplicationEquipment'),
                new StringField('SkyCondition'),
                new NumericField('AirTemperature'),
                new NumericField('WindVelocity'),
                new StringField('WindDirection'),
                new NumericField('LinearFeet'),
                new NumericField('SquareFeet'),
                new NumericField('CubicFeet'),
                new StringField('Comment'),
                new StringField('Technician'),
                new StringField('TechnicianName'),
                new StringField('Device'),
                new DateTimeField('WorkDate'),
                new DateTimeField('DateApplied'),
                new StringField('AreasApplied', true),
                new StringField('TargetPests', true),
                new StringField('TargetPestDescriptions', true),
            ],
            true,
        ),
        new StringField('TargetPests', true),
        new RecordField(
            'Technicians',
            [
                new Int64Field('Position'),
                new Int64Field('TechID'),
                new StringField('Code'),
                new StringField('FirstName'),
                new StringField('LastName'),
                new NumericField('Commission'),
                new NumericField('Bonus'),
                new NumericField('Share'),
                new BooleanField('NoCommission'),
                new StringField('SignatureFilename'),
                new StringField('Username'),
            ],
            true,
        ),
        new RecordField('UserDefinedFields', UserDefinedFields, true),
        new RecordField('PdfUrls', PdfUrlFields),
        new RecordField(
            'Applications',
            [
                new StringField('ApplyFromType'),
                new Int64Field('ApplyFromID'),
                new NumericField('Amount'),
                new BooleanField('Committed'),
                new RecordField('Payment', [
                    new Int64Field('PaymentID'),
                    new Int64Field('BillToID'),
                    new Int64Field('BatchNumber'),
                    new Int64Field('BranchID'),
                    new StringField('Branch'),
                    new DateTimeField('PaymentDate'),
                    new NumericField('Amount'),
                    new NumericField('Balance'),
                    new StringField('Reference'),
                    new StringField('MethodOfPayment'),
                    new StringField('GLCode'),
                    new StringField('Service'),
                    new StringField('ServiceDescription'),
                    new BooleanField('Committed'),
                    new StringField('PaymentType'),
                    new StringField('AdjustmentReason'),
                    new Int64Field('RelatedPaymentID'),
                ]),
                new RecordField('Adjustment', [
                    new Int64Field('PaymentID'),
                    new Int64Field('BillToID'),
                    new Int64Field('BatchNumber'),
                    new Int64Field('BranchID'),
                    new StringField('Branch'),
                    new DateTimeField('PaymentDate'),
                    new NumericField('Amount'),
                    new NumericField('Balance'),
                    new StringField('Reference'),
                    new StringField('MethodOfPayment'),
                    new StringField('GLCode'),
                    new StringField('Service'),
                    new StringField('ServiceDescription'),
                    new BooleanField('Committed'),
                    new StringField('PaymentType'),
                    new StringField('AdjustmentReason'),
                    new Int64Field('RelatedPaymentID'),
                ]),
                new RecordField('CreditMemo', [
                    new Int64Field('InvoiceID'),
                    new Int64Field('LocationID'),
                    new Int64Field('BillToID'),
                    new Int64Field('SetupID'),
                    new StringField('InvoiceNumber'),
                    new StringField('Branch'),
                    new Int64Field('BranchID'),
                    new Int64Field('ParentInvoiceID'),
                    new StringField('ServiceCode'),
                    new StringField('Description'),
                    new NumericField('SubTotal'),
                    new NumericField('Tax'),
                    new RecordField('TaxDetails', TaxDetailsFields, true),
                    new NumericField('Total'),
                    new NumericField('Balance'),
                    new DateTimeField('InvoiceDate'),
                    new DateTimeField('WorkDate'),
                    new DateTimeField('DueDate'),
                    new NumericField('Duration'),
                    new StringField('TimeRange'),
                    new StringField('InvoiceType'),
                    new StringField('Origin'),
                    new StringField('Tech1'),
                    new Int64Field('TechID1'),
                    new StringField('Route'),
                    new StringField('ConsolidatedInvoiceNum'),
                    new DateTimeField('ConsolidatedInvoiceDate'),
                    new RecordField('PdfUrls', PdfUrlFields),
                    new BooleanField('AutoBill'),
                    new StringField('BundleName'),
                    new StringField('DiscountCode'),
                    new Int64Field('LocationBundleID'),
                    new Int64Field('OrderID'),
                    new StringField('OrderNumber'),
                    new NumericField('UncommittedBalance'),
                    new StringField('ExternalIdentifier'),
                ]),
                new RecordField('PendingCreditMemo', [
                    new Int64Field('OrderID'),
                    new Int64Field('LocationID'),
                    new Int64Field('BillToID'),
                    new Int64Field('SetupID'),
                    new StringField('LeadID'),
                    new StringField('OrderNumber'),
                    new StringField('Branch'),
                    new Int64Field('BranchID'),
                    new Int64Field('ParentOrderID'),
                    new StringField('LocationInstructions'),
                    new StringField('ServiceInstructions'),
                    new StringField('OrderInstructions'),
                    new StringField('TechnicianComment'),
                    new BooleanField('InProgress'),
                    new BooleanField('Posted'),
                    new StringField('ServiceCode'),
                    new StringField('Description'),
                    new NumericField('SubTotal'),
                    new NumericField('Tax'),
                    new RecordField('TaxDetails', TaxDetailsFields, true),
                    new NumericField('Total'),
                    new DateTimeField('WorkDate'),
                    new StringField('TimeRange'),
                    new BooleanField('Locked'),
                    new NumericField('Duration'),
                    new StringField('OrderType'),
                    new StringField('Origin'),
                    new StringField('Tech1'),
                    new Int64Field('TechID1'),
                    new StringField('Route'),
                    new RecordField('PdfUrls', PdfUrlFields),
                    new RecordField('UserDefinedFields', UserDefinedFields, true),
                    new StringField('BundleName'),
                    new StringField('DiscountCode'),
                    new Int64Field('LocationBundleID'),
                    new Int64Field('BatchNumber'),
                    new StringField('ExternalIdentifier'),
                ]),
                new RecordField('ReversePayment', [
                    new Int64Field('PaymentID'),
                    new Int64Field('BillToID'),
                    new Int64Field('BatchNumber'),
                    new Int64Field('BranchID'),
                    new StringField('Branch'),
                    new DateTimeField('PaymentDate'),
                    new NumericField('Amount'),
                    new NumericField('Balance'),
                    new StringField('Reference'),
                    new StringField('MethodOfPayment'),
                    new StringField('GlCode'),
                    new StringField('Service'),
                    new StringField('ServiceDescription'),
                    new BooleanField('Committed'),
                    new StringField('PaymentType'),
                    new StringField('AdjustmentReason'),
                    new Int64Field('RelatedPaymentID'),
                ]),
            ],
            true,
        ),
        new RecordField(
            'AppliedTo',
            [
                new StringField('ApplyToType'),
                new Int64Field('ApplyToID'),
                new NumericField('Amount'),
                new BooleanField('Committed'),
                new StringField('AdjustmentReason'),
                new NumericField('AdjustmentAmount'),
                new Int64Field('ServiceID'),
                new RecordField('Invoice', [
                    new Int64Field('InvoiceID'),
                    new Int64Field('LocationID'),
                    new Int64Field('BillToID'),
                    new Int64Field('SetupID'),
                    new StringField('InvoiceNumber'),
                    new StringField('Branch'),
                    new Int64Field('BranchID'),
                    new Int64Field('ParentInvoiceID'),
                    new StringField('ServiceCode'),
                    new StringField('Description'),
                    new NumericField('SubTotal'),
                    new NumericField('Tax'),
                    new RecordField('TaxDetails', TaxDetailsFields, true),
                    new NumericField('Total'),
                    new NumericField('Balance'),
                    new DateTimeField('InvoiceDate'),
                    new DateTimeField('WorkDate'),
                    new DateTimeField('DueDate'),
                    new NumericField('Duration'),
                    new StringField('TimeRange'),
                    new StringField('InvoiceType'),
                    new StringField('Origin'),
                    new StringField('Tech1'),
                    new Int64Field('TechID1'),
                    new StringField('Route'),
                    new StringField('ConsolidatedInvoiceNum'),
                    new DateTimeField('ConsolidatedInvoiceDate'),
                    new RecordField('PdfUrls', PdfUrlFields),
                    new BooleanField('AutoBill'),
                    new StringField('BundleName'),
                    new StringField('DiscountCode'),
                    new Int64Field('LocationBundleID'),
                    new Int64Field('OrderID'),
                    new StringField('OrderNumber'),
                    new NumericField('UncommittedBalance'),
                    new StringField('ExternalIdentifier'),
                ]),
                new RecordField('ServiceOrder', [
                    new Int64Field('OrderID'),
                    new Int64Field('LocationID'),
                    new Int64Field('BillToID'),
                    new Int64Field('SetupID'),
                    new Int64Field('LeadID'),
                    new StringField('OrderNumber'),
                    new StringField('Branch'),
                    new Int64Field('BranchID'),
                    new Int64Field('ParentOrderID'),
                    new StringField('LocationInstructions'),
                    new StringField('ServiceInstructions'),
                    new StringField('OrderInstructions'),
                    new StringField('TechnicianComment'),
                    new BooleanField('InProgress'),
                    new BooleanField('Posted'),
                    new StringField('ServiceCode'),
                    new StringField('Description'),
                    new NumericField('SubTotal'),
                    new NumericField('Tax'),
                    new RecordField('TaxDetails', TaxDetailsFields, true),
                    new NumericField('Total'),
                    new DateTimeField('WorkDate'),
                    new StringField('TimeRange'),
                    new BooleanField('Locked'),
                    new NumericField('Duration'),
                    new StringField('OrderType'),
                    new StringField('Origin'),
                    new StringField('Tech1'),
                    new Int64Field('TechID1'),
                    new StringField('Route'),
                    new RecordField('PdfUrls', PdfUrlFields),
                    new RecordField('UserDefinedFields', UserDefinedFields, true),
                    new StringField('BundleName'),
                    new StringField('DiscountCode'),
                    new Int64Field('LocationBundleID'),
                    new Int64Field('BatchNumber'),
                    new StringField('ExternalIdentifier'),
                ]),
                new RecordField('ServiceSetup', [
                    new Int64Field('SetupID'),
                    new Int64Field('ProgramID'),
                    new Int64Field('LocationID'),
                    new StringField('ServiceCode'),
                    new NumericField('DiscountPercentage'),
                    new BooleanField('AnnualAdvanceRenewal'),
                    new BooleanField('IncludeInitial'),
                ]),
                new RecordField('Renewal', [
                    new Int64Field('SetupID'),
                    new Int64Field('LocationID'),
                    new DateTimeField('StartDate'),
                    new DateTimeField('RenewalDate'),
                    new NumericField('RenewalPrice'),
                    new BooleanField('CreateInvoice'),
                    new DateTimeField('InvoiceDate'),
                    new BooleanField('CreateServiceOrder'),
                    new StringField('OrderType'),
                    new DateTimeField('WorkDate'),
                    new NumericField('Duration'),
                    new StringField('TimeRange'),
                    new StringField('Color'),
                    new Int64Field('TechID1'),
                    new NumericField('TechBonus1'),
                    new NumericField('TechShare1'),
                    new BooleanField('TechNoCommission1'),
                    new Int64Field('TechID2'),
                    new NumericField('TechBonus2'),
                    new NumericField('TechShare2'),
                    new BooleanField('TechNoCommission2'),
                    new Int64Field('TechID3'),
                    new NumericField('TechBonus3'),
                    new NumericField('TechShare3'),
                    new BooleanField('TechNoCommission3'),
                    new Int64Field('TechID4'),
                    new NumericField('TechBonus4'),
                    new NumericField('TechShare4'),
                    new BooleanField('TechNoCommission4'),
                    new Int64Field('TechID5'),
                    new NumericField('TechBonus5'),
                    new NumericField('TechShare5'),
                    new BooleanField('TechNoCommission5'),
                    new BooleanField('AnnualAdvanceRenewal'),
                    new NumericField('RenewalInterval'),
                    new BooleanField('AdvanceRenewalOnly'),
                    new StringField('RenewSetupIDs'),
                    new BooleanField('AdvanceSAD'),
                    new StringField('AsfSetupIDs'),
                ]),
            ],
            true,
        ),
        new StringField('BundleName'),
        new StringField('DiscountCode'),
        new Int64Field('OpportunityId'),
        new Int64Field('LocationBundleID'),
        new Int64Field('OrderID'),
        new StringField('ExternalIdentifier'),
        new RecordField(
            'ServiceOrderAttributes',
            [
                new Int64Field('AttributeAssignmentID'),
                new Int64Field('OrderID'),
                new Int64Field('InvoiceID'),
                new Int64Field('AttributeID'),
                new StringField('Category'),
                new StringField('Description'),
                new StringField('Type'),
                new StringField('Answer'),
                new StringField('YesText'),
                new StringField('NoText'),
                new StringField('CheckboxText'),
            ],
            true,
        ),
    ],
});
